### ISSUE TITLE
Create Database Adapters

### ISSUE THREAD

**Issue by jonguertin** [2103-USD/tech-phantoms#2]
- [x] getProductById
- [x] getProductById(id) - return the product
- [x] getAllProducts - select and return an array of all products
- [x] createProduct
- [x] createProduct(product) - return the new product

**Comment by jonguertin** [comment]
getProductById

getProductById(id)
return the product

getAllProducts
select and return an array of all products

createProduct

createProduct(product)
return the new product

**Comment by VW71superbeetle** [comment]
done
